spring:
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/category/**
          filters:
            - AuthenticationFilter

        - id: discount-service
          uri: lb://DISCOUNT-SERVICE
          predicates:
            - Path=/api/v1/discount/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - AuthenticationFilter